/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PredictionRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LOCK_FEE"
      | "SLIPPAGE_TOLERANCE_BP"
      | "WETH"
      | "compensationPool"
      | "executeSetRelayer"
      | "getUserPredictions"
      | "owner"
      | "predictionCounter"
      | "predictions"
      | "priceFeed"
      | "relayerAddress"
      | "renounceOwnership"
      | "setPriceFeed"
      | "setRelayerAddress"
      | "setTimelock"
      | "submitPredictionState"
      | "timelock"
      | "transferOwnership"
      | "verifyAndPayout"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PredictionSubmitted"
      | "VerificationFailed"
      | "VerificationResult"
  ): EventFragment;

  encodeFunctionData(functionFragment: "LOCK_FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "SLIPPAGE_TOLERANCE_BP",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "compensationPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeSetRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPredictions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "predictionCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "predictions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "priceFeed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "relayerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceFeed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRelayerAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTimelock",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitPredictionState",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "timelock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndPayout",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "LOCK_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SLIPPAGE_TOLERANCE_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "compensationPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSetRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPredictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "predictionCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "priceFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "relayerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRelayerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitPredictionState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timelock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndPayout",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictionSubmittedEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    predictedBP: BigNumberish,
    txSwapHash: BytesLike
  ];
  export type OutputTuple = [
    id: bigint,
    user: string,
    predictedBP: bigint,
    txSwapHash: string
  ];
  export interface OutputObject {
    id: bigint;
    user: string;
    predictedBP: bigint;
    txSwapHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationFailedEvent {
  export type InputTuple = [
    predictionId: BigNumberish,
    predictor: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    predictionId: bigint,
    predictor: string,
    reason: string
  ];
  export interface OutputObject {
    predictionId: bigint;
    predictor: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationResultEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    isAccurate: boolean,
    actualSlippageBP: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    user: string,
    isAccurate: boolean,
    actualSlippageBP: bigint
  ];
  export interface OutputObject {
    id: bigint;
    user: string;
    isAccurate: boolean;
    actualSlippageBP: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionRegistry;
  waitForDeployment(): Promise<this>;

  interface: PredictionRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LOCK_FEE: TypedContractMethod<[], [bigint], "view">;

  SLIPPAGE_TOLERANCE_BP: TypedContractMethod<[], [bigint], "view">;

  WETH: TypedContractMethod<[], [string], "view">;

  compensationPool: TypedContractMethod<[], [string], "view">;

  executeSetRelayer: TypedContractMethod<
    [_relayer: AddressLike],
    [void],
    "nonpayable"
  >;

  getUserPredictions: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  predictionCounter: TypedContractMethod<[], [bigint], "view">;

  predictions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, boolean] & {
        predictor: string;
        tokenIn: string;
        tokenOut: string;
        amountIn: bigint;
        predictedSlippageBP: bigint;
        quotePrice: bigint;
        hasBeenVerified: boolean;
      }
    ],
    "view"
  >;

  priceFeed: TypedContractMethod<[], [string], "view">;

  relayerAddress: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPriceFeed: TypedContractMethod<
    [_priceFeed: AddressLike],
    [void],
    "nonpayable"
  >;

  setRelayerAddress: TypedContractMethod<
    [_relayer: AddressLike],
    [void],
    "nonpayable"
  >;

  setTimelock: TypedContractMethod<
    [_timelock: AddressLike],
    [void],
    "nonpayable"
  >;

  submitPredictionState: TypedContractMethod<
    [
      _tokenIn: AddressLike,
      _tokenOut: AddressLike,
      _amountIn: BigNumberish,
      _predictedSlippageBP: BigNumberish,
      _quotePrice: BigNumberish,
      _expectedSwapTxHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  timelock: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyAndPayout: TypedContractMethod<
    [
      _predictionId: BigNumberish,
      _amountOutActual: BigNumberish,
      _actualSlippageBP: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LOCK_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SLIPPAGE_TOLERANCE_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WETH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "compensationPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "executeSetRelayer"
  ): TypedContractMethod<[_relayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getUserPredictions"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "predictionCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "predictions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, boolean] & {
        predictor: string;
        tokenIn: string;
        tokenOut: string;
        amountIn: bigint;
        predictedSlippageBP: bigint;
        quotePrice: bigint;
        hasBeenVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "priceFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "relayerAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceFeed"
  ): TypedContractMethod<[_priceFeed: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRelayerAddress"
  ): TypedContractMethod<[_relayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTimelock"
  ): TypedContractMethod<[_timelock: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitPredictionState"
  ): TypedContractMethod<
    [
      _tokenIn: AddressLike,
      _tokenOut: AddressLike,
      _amountIn: BigNumberish,
      _predictedSlippageBP: BigNumberish,
      _quotePrice: BigNumberish,
      _expectedSwapTxHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "timelock"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyAndPayout"
  ): TypedContractMethod<
    [
      _predictionId: BigNumberish,
      _amountOutActual: BigNumberish,
      _actualSlippageBP: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PredictionSubmitted"
  ): TypedContractEvent<
    PredictionSubmittedEvent.InputTuple,
    PredictionSubmittedEvent.OutputTuple,
    PredictionSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationFailed"
  ): TypedContractEvent<
    VerificationFailedEvent.InputTuple,
    VerificationFailedEvent.OutputTuple,
    VerificationFailedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationResult"
  ): TypedContractEvent<
    VerificationResultEvent.InputTuple,
    VerificationResultEvent.OutputTuple,
    VerificationResultEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PredictionSubmitted(uint256,address,uint256,bytes32)": TypedContractEvent<
      PredictionSubmittedEvent.InputTuple,
      PredictionSubmittedEvent.OutputTuple,
      PredictionSubmittedEvent.OutputObject
    >;
    PredictionSubmitted: TypedContractEvent<
      PredictionSubmittedEvent.InputTuple,
      PredictionSubmittedEvent.OutputTuple,
      PredictionSubmittedEvent.OutputObject
    >;

    "VerificationFailed(uint256,address,string)": TypedContractEvent<
      VerificationFailedEvent.InputTuple,
      VerificationFailedEvent.OutputTuple,
      VerificationFailedEvent.OutputObject
    >;
    VerificationFailed: TypedContractEvent<
      VerificationFailedEvent.InputTuple,
      VerificationFailedEvent.OutputTuple,
      VerificationFailedEvent.OutputObject
    >;

    "VerificationResult(uint256,address,bool,uint256)": TypedContractEvent<
      VerificationResultEvent.InputTuple,
      VerificationResultEvent.OutputTuple,
      VerificationResultEvent.OutputObject
    >;
    VerificationResult: TypedContractEvent<
      VerificationResultEvent.InputTuple,
      VerificationResultEvent.OutputTuple,
      VerificationResultEvent.OutputObject
    >;
  };
}
