/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockAggregator,
  MockAggregatorInterface,
} from "../../../contracts/mocks/MockAggregator";

const _abi = [
  {
    inputs: [
      {
        internalType: "int256",
        name: "_initialAnswer",
        type: "int256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "description",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint80",
        name: "_roundId",
        type: "uint80",
      },
    ],
    name: "getRoundData",
    outputs: [
      {
        internalType: "uint80",
        name: "roundId",
        type: "uint80",
      },
      {
        internalType: "int256",
        name: "answer",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "startedAt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "updatedAt",
        type: "uint256",
      },
      {
        internalType: "uint80",
        name: "answeredInRound",
        type: "uint80",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "latestRoundData",
    outputs: [
      {
        internalType: "uint80",
        name: "roundId",
        type: "uint80",
      },
      {
        internalType: "int256",
        name: "answer",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "startedAt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "updatedAt",
        type: "uint256",
      },
      {
        internalType: "uint80",
        name: "answeredInRound",
        type: "uint80",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "_answer",
        type: "int256",
      },
    ],
    name: "setLatestAnswer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "version",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161027d38038061027d83398101604081905261002f9161003b565b60005542600155610054565b60006020828403121561004d57600080fd5b5051919050565b61021a806100636000396000f3fe608060405234801561001057600080fd5b50600436106100625760003560e01c806304ea97b014610067578063313ce5671461008057806354fd4d50146100945780637284e416146100a35780639a6fc8f5146100e2578063feaf968c14610138575b600080fd5b61007e610075366004610149565b60005542600155565b005b604051600081526020015b60405180910390f35b6040516001815260200161008b565b604080518082018252601881527f4d6f636b20536c6970706167652041676772656761746f7200000000000000006020820152905161008b9190610162565b6101016100f03660046101b1565b600054600154919290919081908490565b6040805169ffffffffffffffffffff968716815260208101959095528401929092526060830152909116608082015260a00161008b565b600054600180549091908083610101565b60006020828403121561015b57600080fd5b5035919050565b60006020808352835180602085015260005b8181101561019057858101830151858201604001528201610174565b506000604082860101526040601f19601f8301168501019250505092915050565b6000602082840312156101c357600080fd5b813569ffffffffffffffffffff811681146101dd57600080fd5b939250505056fea26469706673582212203c485997aebb51a321635ca900ef92faaa351f90fb1488b27f2c96d4a08d390264736f6c63430008180033";

type MockAggregatorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockAggregatorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockAggregator__factory extends ContractFactory {
  constructor(...args: MockAggregatorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _initialAnswer: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_initialAnswer, overrides || {});
  }
  override deploy(
    _initialAnswer: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_initialAnswer, overrides || {}) as Promise<
      MockAggregator & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockAggregator__factory {
    return super.connect(runner) as MockAggregator__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockAggregatorInterface {
    return new Interface(_abi) as MockAggregatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockAggregator {
    return new Contract(address, _abi, runner) as unknown as MockAggregator;
  }
}
