/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iUniswapRouterSol from "./IUniswapRouter.sol";
export type { iUniswapRouterSol };
export type { IWETH } from "./IWETH";
