/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interface from "./interface";
export * as mocks from "./mocks";
export { CompensationPool__factory } from "./CompensationPool__factory";
export { PredictionRegistry__factory } from "./PredictionRegistry__factory";
